

services:
  postgres:
    image: postgres:15-alpine
    container_name: docai_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: docai
      POSTGRES_PASSWORD: docai_password
      POSTGRES_DB: docai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: docai_minio
    ports:
      - "9095:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
